export const moviesData = [
    {
    id: '1',
    original_title: 'Interstellar',
    year: 2014,
    spanish_title: 'Interestelar',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    runtime: '2h 49m',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    genres: ['Adventure', 'Drama', 'Science Fiction'],
    rating: 8.3,
    director: 'Christopher Nolan',
    cast: [
      { name: 'Matthew McConaughey', role: 'Cooper' },
      { name: 'Anne Hathaway', role: 'Brand' },
      { name: 'Jessica Chastain', role: 'Murph' },
      { name: 'Michael Caine', role: 'Professor Brand' },
      { name: 'Matt Damon', role: 'Mann' }
    ],
    country: 'United States',
    watchedAt: '2025-06-21',
    isWatched: true,
    isOnWatchlist: true,
    userRating: 10,
    isLogged: true,
  },
    {
    id: '2',
    original_title: 'The Dark Knight',
    year: 2008,
    spanish_title: 'El caballero oscuro',
    poster_path: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    runtime: '2h 32m',
    overview: 'When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 8.5,
    director: 'Christopher Nolan',
    cast: [
      { name: 'Christian Bale', role: 'Bruce Wayne / Batman' },
      { name: 'Heath Ledger', role: 'Joker' },
      { name: 'Aaron Eckhart', role: 'Harvey Dent' },
      { name: 'Michael Caine', role: 'Alfred Pennyworth' },
      { name: 'Gary Oldman', role: 'James Gordon' }
    ],
    country: 'United States',
    watchedAt: '2025-05-30',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },
    {
    id: '3',
    original_title: 'Parasite',
    year: 2019,
    spanish_title: 'Parásitos',
    poster_path: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    runtime: '2h 12m',
    overview: 'All unemployed, Ki-taek’s family takes peculiar interest in the wealthy family living in their neighborhood. They infiltrate the family by posing as unrelated, highly qualified individuals.',
    genres: ['Comedy', 'Thriller', 'Drama'],
    rating: 8.5,
    director: 'Bong Joon-ho',
    cast: [
      { name: 'Song Kang-ho', role: 'Kim Ki-taek' },
      { name: 'Cho Yeo-jeong', role: 'Park Yeon-kyo' },
      { name: 'Choi Woo-shik', role: 'Ki-woo' },
      { name: 'Park So-dam', role: 'Ki-jung' },
      { name: 'Lee Sun-kyun', role: 'Dong-ik' }
    ],
    country: 'South Korea',
    watchedAt: '2025-06-25',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 7,
    isLogged: true,
  },
    {
    id: '4',
    original_title: 'The Godfather',
    year: 1972,
    spanish_title: 'El padrino',
    poster_path: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    runtime: '2h 55m',
    overview: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    genres: ['Crime', 'Drama'],
    rating: 8.7,
    director: 'Francis Ford Coppola',
    cast: [
      { name: 'Marlon Brando', role: 'Don Vito Corleone' },
      { name: 'Al Pacino', role: 'Michael Corleone' },
      { name: 'James Caan', role: 'Sonny Corleone' },
      { name: 'Diane Keaton', role: 'Kay Adams' },
      { name: 'Robert Duvall', role: 'Tom Hagen' }
    ],
    country: 'United States',
    watchedAt: '2025-07-11',
    isWatched: true,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },
   {id: '5',
    original_title: 'Back to the Future',
    year: 1985,
    spanish_title: 'Regreso al futuro',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/fNOH9f1aA7XRTzl1sAOx9iF553Q.jpg',
    runtime: '1h 56m',
    overview: 'A teenager is accidentally sent back in time to 1955, where he must ensure that his parents fall in love or risk altering the course of history.',
    genres: ['Adventure', 'Comedy', 'Science Fiction'],
    rating: 8.5,
    director: 'Robert Zemeckis',
    cast: [
      { name: 'Michael J. Fox', role: 'Marty McFly' },
      { name: 'Christopher Lloyd', role: 'Doc Brown' },
      { name: 'Lea Thompson', role: 'Lorraine Baines' },
      { name: 'Crispin Glover', role: 'George McFly' },
      { name: 'Thomas F. Wilson', role: 'Biff Tannen' }
    ],
    country: 'United States',
    watchedAt: '2025-07-31',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },
  {
    id: '6',
    original_title: 'Inception',
    year: 2010,
    spanish_title: 'Origen',
    poster_path: 'https://image.tmdb.org/t/p/w500/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
    runtime: '2h 28m',
    overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.',
    genres: ['Action', 'Science Fiction'],
    rating: 8.4,
    director: 'Christopher Nolan',
    cast: [
      { name: 'Leonardo DiCaprio', role: 'Dom Cobb' },
      { name: 'Joseph Gordon-Levitt', role: 'Arthur' },
      { name: 'Elliot Page', role: 'Ariadne' },
      { name: 'Tom Hardy', role: 'Eames' },
      { name: 'Ken Watanabe', role: 'Saito' }
    ],
    country: 'United States',
    watchedAt: '2025-07-10',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 9,
    isLogged: true,
  },
    {
    id: '7',
    original_title: 'La La Land',
    year: 2016,
    spanish_title: 'La ciudad de las estrellas',
    poster_path: 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
    runtime: '2h 8m',
    overview: 'A jazz musician and an aspiring actress fall in love but struggle to maintain their relationship as they pursue their dreams in Los Angeles.',
    genres: ['Comedy', 'Drama', 'Romance'],
    rating: 8.0,
    director: 'Damien Chazelle',
    cast: [
      { name: 'Ryan Gosling', role: 'Sebastian' },
      { name: 'Emma Stone', role: 'Mia' },
      { name: 'John Legend', role: 'Keith' },
      { name: 'Rosemarie DeWitt', role: 'Laura' },
      { name: 'J.K. Simmons', role: 'Bill' }
    ],
    country: 'United States',
    watchedAt: '2025-06-30',
    isWatched: true,
    isOnWatchlist: true,
    userRating: 8,
    isLogged: true,
  },
    {
    id: '8',
    original_title: 'Jurassic World: Rebirth',
    year: 2025,
    spanish_title: 'Jurassic World: Renacimiento',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg',
    runtime: '2h 30m',
    overview: 'In a world where dinosaurs and humans coexist, a new threat emerges that could endanger both species. A group of scientists and adventurers must work together to save the planet.',
    genres: ['Adventure', 'Science Fiction'],
    rating: 7.9,
    director: 'Colin Trevorrow',
    cast: [
      { name: 'Chris Pratt', role: 'Owen Grady' },
      { name: 'Bryce Dallas Howard', role: 'Claire Dearing' },
      { name: 'Laura Dern', role: 'Dr. Ellie Sattler' },
      { name: 'Sam Neill', role: 'Dr. Alan Grant' },
      { name: 'Jeff Goldblum', role: 'Dr. Ian Malcolm' }
    ],
    country: 'United States',
    watchedAt: null,
    isWatched: false,
    isOnWatchlist: false,
    userRating: null,
    isLogged: false,
  },
    {
    id: '9',
    original_title: 'How to Train Your Dragon',
    year: 2025,
    spanish_title: 'Cómo entrenar a tu dragón',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/q5pXRYTycaeW6dEgsCrd4mYPmxM.jpg',
    runtime: '1h 38m',
    overview: 'A young Viking befriends a dragon and learns that there is more to these creatures than meets the eye.',
    genres: ['Animation', 'Adventure', 'Family'],
    rating: 8.1,
    director: 'Dean DeBlois',
    cast: [
      { name: 'Jay Baruchel', role: 'Hiccup' },
      { name: 'America Ferrera', role: 'Astrid' },
      { name: 'Gerard Butler', role: 'Stoick' },
      { name: 'Craig Ferguson', role: 'Gobber' },
      { name: 'Kristen Wiig', role: 'Ruffnut' }
    ],
    country: 'United States',
    watchedAt: null,
    isWatched: false,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },
  
  {id: '10',
    original_title: 'Superman',
    year: 2025,
    spanish_title: 'Superman',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg',
    runtime: '2h 20m',
    overview: 'Clark Kent, an alien with superhuman abilities, must embrace his destiny as Superman to protect Earth from a powerful threat.',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    rating: 8.0,
    director: 'Zack Snyder',
    cast: [
      { name: 'Henry Cavill', role: 'Clark Kent / Superman' },
      { name: 'Amy Adams', role: 'Lois Lane' },
      { name: 'Michael Shannon', role: 'General Zod' }
    ],
    country: 'United States',
        watchedAt: null,
    isWatched: false,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },
  
    {
    id: '11',
    original_title: '28 years later',
    year: 2025,
    spanish_title: '28 años después',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg',
    runtime: '2h 30m',
    overview: 'In a post-apocalyptic world, survivors must navigate through a landscape filled with mutated creatures and hostile factions to find a safe haven.',
    genres: ['Horror', 'Science Fiction'],
    rating: 7.9,
    director: 'John Smith',
    cast: [
      { name: 'Actor 1', role: 'Survivor 1' },
      { name: 'Actor 2', role: 'Survivor 2' },
      { name: 'Actor 3', role: 'Survivor 3' }
    ],
    country: 'United States',
        watchedAt: null,
    isWatched: false,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },
  {
    id: '12',
    original_title: 'The Fantastic Four',
    year: 2025,
    spanish_title: 'Los Cuatro Fantásticos',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/x26MtUlwtWD26d0G0FXcppxCJio.jpg',
    runtime: '2h 10m',
    overview: 'A team of four astronauts gains superpowers after a cosmic accident and must use their abilities to save the world from a powerful enemy.',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    rating: 7.5,
    director: 'Josh Trank',
    cast: [
      { name: 'Miles Teller', role: 'Reed Richards / Mr. Fantastic' },
      { name: 'Kate Mara', role: 'Sue Storm / Invisible Woman' },
      { name: 'Michael B. Jordan', role: 'Johnny Storm / Human Torch' },
      { name: 'Jamie Bell', role: 'Ben Grimm / The Thing' }
    ],
    country: 'United States',
        watchedAt: null,
    isWatched: false,
    isOnWatchlist: false,
    userRating: null,
    isLogged: false,
  },

 
  {id: '13',
    original_title: 'Speak No Evil',
    year: 2022,
    spanish_title: 'No hables mal',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/6NwAlU6ZH6ua3sYpFAUpUnoKUmi.jpg',
    runtime: '1h 37m',
    overview: 'A Danish family visits a Dutch family they met on vacation, but their seemingly perfect hosts turn out to have sinister intentions.',
    genres: ['Horror', 'Thriller'],
    rating: 7.2,
    director: 'Christian Tafdrup',
    cast: [
      { name: 'Morten Burian', role: 'Abel' },
      { name: 'Sidsel Siem Koch', role: 'Marie' },
      { name: 'Fedja van Huêt', role: 'The Host' }
    ],
    country: 'Denmark',
    watchedAt: null,
    isWatched: false,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },
  {
    id: '14',
    original_title: 'Final Destination Bloodlines',
    year: 2025,
    spanish_title: 'Final Destination Bloodlines',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/6WxhEvFsauuACfv8HyoVX6mZKFj.jpg',
    runtime: '1h 50m',
    overview: 'A young FBI cadet must confide in an incarcerated and manipulative killer to receive his help on catching another serial killer.',
    genres: ['Horror', 'Mystery'],
    rating: 8.6,
    director: '',
    cast: [
      { name: 'John Doe', role: 'Agent Smith' },
      { name: 'Jane Doe', role: 'Agent Johnson' },
      { name: 'Alice Smith', role: 'Victim Survivor' },
      { name: 'Bob Brown', role: 'Killer' }
    ],
    country: 'United States',
    watchedAt: null,
    isWatched: false,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },
  {
    id: '15',
    original_title: 'Everything You Always Wanted to Know About Sex *But Were Afraid to Ask',
    year: 1972,
    spanish_title: 'Todo lo que siempre quiso saber sobre el sexo *pero nunca se atrevió a preguntar',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/A1ZNhNd8FV8kCW39OeDelokT0tv.jpg',
    runtime: '1h 28m',
    overview: 'Seven short vignettes that address various sexual questions and concerns, from the absurd to the profound.',
    genres: ['Comedy'],
    rating: 7.0,
    director: 'Woody Allen',
    cast: [
      { name: 'Woody Allen', role: 'Various' },
      { name: 'Gene Wilder', role: 'Dr. Ross' },
      { name: 'Louise Lasser', role: 'Herself' },
      { name: 'John Carradine', role: 'The King' },
      { name: 'Heather MacRae', role: 'The Queen' }
    ],
    country: 'United States',
    watchedAt: '2025-07-09',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
    },
    {
    id: '16',
    original_title: 'The Lord of the Rings: The Fellowship of the Ring',  
    year: 2001,
    spanish_title: 'El Señor de los Anillos: La Comunidad del Anillo',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    runtime: '2h 58m',
    overview: 'A young hobbit, Frodo Baggins, is tasked with destroying a powerful ring that could bring about the end of Middle-earth.',
    genres: ['Adventure', 'Fantasy'],
    rating: 8.8,
    director: 'Peter Jackson',
    cast: [
      { name: 'Elijah Wood', role: 'Frodo Baggins' },
      { name: 'Ian McKellen', role: 'Gandalf' },
      { name: 'Viggo Mortensen', role: 'Aragorn' },
      { name: 'Sean Astin', role: 'Samwise Gamgee' },
      { name: 'Orlando Bloom', role: 'Legolas' }
    ],
    country: 'New Zealand',
    watchedAt: '2025-07-14',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 10,
    isLogged: true,
    },
  {
    id: '17',
    original_title: 'The Lord of the Rings: The Two Towers',
    year: 2002,
    spanish_title: 'El Señor de los Anillos: Las Dos Torres', 
    poster_path: 'https://www.themoviedb.org/t/p/w1280/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg',
    runtime: '2h 59m',
    overview: 'Frodo and Sam continue their journey to Mordor, while Aragorn, Legolas, and Gimli pursue the kidnapped Merry and Pippin.',
    genres: ['Adventure', 'Fantasy'],
    rating: 8.7,
    director: 'Peter Jackson',
    cast: [
      { name: 'Elijah Wood', role: 'Frodo Baggins' },
      { name: 'Ian McKellen', role: 'Gandalf' },
      { name: 'Viggo Mortensen', role: 'Aragorn' },
      { name: 'Sean Astin', role: 'Samwise Gamgee' },
      { name: 'Orlando Bloom', role: 'Legolas' }
    ],
    country: 'New Zealand',
    watchedAt: '2025-07-16',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 10,
    isLogged: true,
  },
  {
    id: '18',
    original_title: 'The Lord of the Rings: The Return of the King',
    year: 2003,
    spanish_title: 'El Señor de los Anillos: El Retorno del Rey',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
    runtime: '3h 21m',
    overview: 'The final battle for Middle-earth begins as Frodo and Sam continue their journey to destroy the One Ring.',
    genres: ['Adventure', 'Fantasy'],
    rating: 8.9,
    director: 'Peter Jackson',
    cast: [
      { name: 'Elijah Wood', role: 'Frodo Baggins' },
      { name: 'Ian McKellen', role: 'Gandalf' },
      { name: 'Viggo Mortensen', role: 'Aragorn' },
      { name: 'Sean Astin', role: 'Samwise Gamgee' },
      { name: 'Orlando Bloom', role: 'Legolas' }
    ],
    country: 'New Zealand',
    watchedAt: '2025-07-17',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 10,
    isLogged: true,
  },
  { 
    id: '19',
    original_title: 'Minecrafter: The Movie',
    year: 2025,
    spanish_title: 'Minecrafter: La Película',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/yFHHfHcUgGAxziP1C3lLt0q2T4s.jpg',
    runtime: '2h 15m',
    overview: 'In a world made entirely of blocks, a young Minecrafter embarks on an epic quest to save their village from a mysterious force threatening to destroy everything they know.',
    genres: ['Adventure', 'Fantasy'],
    rating: 7.5,
    director: 'Jane Doe',
    cast: [
      { name: 'John Doe', role: 'Hero' },
      { name: 'Jane Smith', role: 'Villain' },
      { name: 'Bob Johnson', role: 'Sidekick' }
    ],
    country: 'United States',
    watchedAt: null,
    isWatched: false,
    isOnWatchlist: false,
    userRating: null,
    isLogged: false,
  },
  {
    id: '20',
    original_title: 'The Shawshank Redemption',
    year: 1994,
    spanish_title: 'Cadena perpetua',
    poster_path: 'https://image.tmdb.org/t/p/w500/hBcY0fE9pfXzvVaY4GKarweriG2.jpg',
    runtime: '2h 22m',
    overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    genres: ['Drama', 'Crime'],
    rating: 8.7,
    director: 'Frank Darabont',
    cast: [
      { name: 'Tim Robbins', role: 'Andy Dufresne' },
      { name: 'Morgan Freeman', role: 'Ellis Boyd Redding' },
      { name: 'Bob Gunton', role: 'Warden Norton' },
      { name: 'William Sadler', role: 'Heywood' },
      { name: 'Clancy Brown', role: 'Captain Hadley' }
    ],
    country: 'United States',
    watchedAt: '2025-06-18',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 10,
    isLogged: true,
  },

  {
    id: '21',
    original_title: 'Pulp Fiction',
    year: 1994,
    spanish_title: 'Tiempos violentos',
    poster_path: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    runtime: '2h 34m',
    overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    genres: ['Crime', 'Drama'],
    rating: 8.5,
    director: 'Quentin Tarantino',
    cast: [
      { name: 'John Travolta', role: 'Vincent Vega' },
      { name: 'Samuel L. Jackson', role: 'Jules Winnfield' },
      { name: 'Uma Thurman', role: 'Mia Wallace' },
      { name: 'Harvey Keitel', role: 'Mr. Wolf' },
      { name: 'Tim Roth', role: 'Pumpkin' }
    ],
    country: 'United States',
    watchedAt: '2025-06-03',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 6,
    isLogged: true,
  },
  {
    id: '22',
    original_title: 'Forrest Gump',
    year: 1994,
    spanish_title: 'Forrest Gump',
    poster_path: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    runtime: '2h 22m',
    overview: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold through the perspective',
    genres: ['Comedy', 'Drama', 'Romance'],
    rating: 8.5,
    director: 'Robert Zemeckis',
    cast: [
      { name: 'Tom Hanks', role: 'Forrest Gump' },
      { name: 'Robin Wright', role: 'Jenny Curran' },
      { name: 'Gary Sinise', role: 'Lieutenant Dan Taylor' },
      { name: 'Mykelti Williamson', role: 'Bubba Blue' },
      { name: 'Sally Field', role: 'Mrs. Gump' }
    ],
    country: 'United States',
    watchedAt: '2025-07-01',
    isWatched: true,
    isOnWatchlist: true,
    userRating: null,
    isLogged: false,
  },

  {
    id: '23',
    original_title: 'Fight Club',
    year: 1999,
    spanish_title: 'El club de la lucha',
    poster_path: 'https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg',
    runtime: '2h 19m',
    overview: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into something much, much more.',
    genres: ['Drama'],
    rating: 8.4,
    director: 'David Fincher',
    cast: [
      { name: 'Brad Pitt', role: 'Tyler Durden' },
      { name: 'Edward Norton', role: 'The Narrator' },
      { name: 'Helena Bonham Carter', role: 'Marla Singer' },
      { name: 'Meat Loaf', role: 'Robert Paulson' },
      { name: 'Zach Grenier', role: 'Richard Chesler' }
    ],
    country: 'United States',
    watchedAt: '2025-07-05',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 5,
    isLogged: true,
  },
  {
    id: '24',
    original_title: 'The Matrix',
    year: 1999,
    spanish_title: 'Matrix',
    poster_path: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    runtime: '2h 16m',
    overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    genres: ['Action', 'Science Fiction'],
    rating: 8.1,
    director: 'The Wachowskis',
    cast: [
      { name: 'Keanu Reeves', role: 'Neo' },
      { name: 'Laurence Fishburne', role: 'Morpheus' },
      { name: 'Carrie-Anne Moss', role: 'Trinity' },
      { name: 'Hugo Weaving', role: 'Agent Smith' },
      { name: 'Joe Pantoliano', role: 'Cypher' }
    ],
    country: 'United States',
    watchedAt: '2025-06-12',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },

   {
    id: '25',
    original_title: 'Whiplash',
    year: 2014,
    spanish_title: 'Whiplash: Música y obsesión',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    runtime: '1h 47m',
    overview: '',
    genres: ['Drama', 'Music'],
    rating: 8.4,
    director: 'Damien Chazelle',
    cast: [
      { name: 'Miles Teller', role: 'Andrew Neiman' },
      { name: 'J.K. Simmons', role: 'Terence Fletcher' },
      { name: 'Melissa Benoist', role: 'Nicole' },
      { name: 'Paul Reiser', role: 'Jim Neiman' },
      { name: 'Austin Stowell', role: 'Ryan Connolly' }
    ],
    country: 'United States',
    watchedAt: '2025-07-02',
    isWatched: true,
    isOnWatchlist: true,
    userRating: 10,
    isLogged: true,
  },
  {
    id: '26',
    original_title: 'The Grand Budapest Hotel',
    year: 2014,
    spanish_title: 'El gran hotel Budapest',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
    runtime: '1h 40m',
    overview: 'The adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend.',
    genres: ['Comedy', 'Drama'],
    rating: 8.1,
    director: 'Wes Anderson',
    cast: [
      { name: 'Ralph Fiennes', role: 'M. Gustave' },
      { name: 'Tony Revolori', role: 'Zero Moustafa' },
      { name: 'F. Murray Abraham', role: 'Mr. Moustafa' },
      { name: 'Jeff Goldblum', role: 'Deputy Vilmos Kovacs' },
      { name: 'Jude Law', role: 'Young Writer' }
    ],
    country: 'Germany',
    watchedAt: '2025-06-20',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },
  {
    id: '27',
    original_title: 'Gladiator',
    year: 2000,
    spanish_title: 'Gladiador',
    poster_path: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    runtime: '2h 35m',
    overview: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    genres: ['Action', 'Drama', 'Adventure'],
    rating: 8.2,
    director: 'Ridley Scott',
    cast: [
      { name: 'Russell Crowe', role: 'Maximus' },
      { name: 'Joaquin Phoenix', role: 'Commodus' },
      { name: 'Connie Nielsen', role: 'Lucilla' },
      { name: 'Oliver Reed', role: 'Proximo' },
      { name: 'Djimon Hounsou', role: 'Juba' }
    ],
    country: 'United Kingdom',
    watchedAt: '2025-07-13',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },
  {
    id: '28',
    original_title: 'Spirited Away',
    year: 2001,
    spanish_title: 'El viaje de Chihiro',
    poster_path: 'https://image.tmdb.org/t/p/w500/oRvMaJOmapypFUcQqpgHMZA6qL9.jpg',
    runtime: '2h 5m',
    overview: 'During her family’s move to the suburbs, a girl enters a world of spirits and must find a way to save her parents and return home.',
    genres: ['Animation', 'Fantasy', 'Family'],
    rating: 8.5,
    director: 'Hayao Miyazaki',
    cast: [
      { name: 'Rumi Hiiragi', role: 'Chihiro' },
      { name: 'Miyu Irino', role: 'Haku' },
      { name: 'Mari Natsuki', role: 'Yubaba' },
      { name: 'Bunta Sugawara', role: 'Kamaji' },
      { name: 'Takehiko Ono', role: 'Lin' }
    ],
    country: 'Japan',
    watchedAt: '2025-06-26',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 9,
    isLogged: true,
  },
  {
    id: '29',
    original_title: 'Se7en',
    year: 1995,
    spanish_title: 'Seven',
    poster_path: 'https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg',
    runtime: '2h 7m',
    overview: 'Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.',
    genres: ['Crime', 'Drama', 'Mystery'],
    rating: 8.4,
    director: 'David Fincher',
    cast: [
      { name: 'Brad Pitt', role: 'Detective David Mills' },
      { name: 'Morgan Freeman', role: 'Detective Somerset' },
      { name: 'Gwyneth Paltrow', role: 'Tracy Mills' },
      { name: 'Kevin Spacey', role: 'John Doe' },
      { name: 'Andrew Kevin Walker', role: 'Mark Swarr' }
    ],
    country: 'United States',
    watchedAt: '2025-06-28',
    isWatched: true,
    isOnWatchlist: false,
    userRating: 9,
    isLogged: true,
  },

  {
    id: '30',
    original_title: 'The Green Mile',
    year: 1999,
    spanish_title: 'Milagros inesperados',
    poster_path: 'https://image.tmdb.org/t/p/w500/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg',
    runtime: '3h 9m',
    overview: 'The lives of guards on Death Row are affected by one of their charges, a gentle giant with a mysterious past.',
    genres: ['Fantasy', 'Drama', 'Crime'],
    rating: 8.5,
    director: 'Frank Darabont',
    cast: [
      { name: 'Tom Hanks', role: 'Paul Edgecomb' },
      { name: 'Michael Clarke Duncan', role: 'John Coffey' },
      { name: 'David Morse', role: 'Brutus "Brutal" Howell' },
      { name: 'Bonnie Hunt', role: 'Jan Edgecomb' },
      { name: 'James Cromwell', role: 'Warden Hal Moores' }
    ],
    country: 'United States',
    watchedAt: '2025-07-07',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 6,
    isLogged: true,
  },
  {
    id: '31',
    original_title: 'Coco',
    year: 2017,
    spanish_title: 'Coco',
    poster_path: 'https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg',
    runtime: '1h 45m',
    overview: 'Aspiring musician Miguel enters the Land of the Dead to find his great-great-grandfather, a legendary singer, and discover his family’s history.',
    genres: ['Animation', 'Family', 'Music'],
    rating: 8.2,
    director: 'Lee Unkrich',
    cast: [
      { name: 'Anthony Gonzalez', role: 'Miguel' },
      { name: 'Gael García Bernal', role: 'Héctor' },
      { name: 'Benjamin Bratt', role: 'Ernesto de la Cruz' },
      { name: 'Alanna Ubach', role: 'Mama Imelda' },
      { name: 'Renée Victor', role: 'Abuelita' }
    ],
    country: 'United States',
    watchedAt: '2025-07-15',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },
  {
    id: '32',
    original_title: 'Joker',
    year: 2019,
    spanish_title: 'Joker',
    poster_path: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    runtime: '2h 2m',
    overview: 'In Gotham City, mentally troubled comedian Arthur Fleck embarks on a downward spiral into insanity while trying to find his place in the world.',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.2,
    director: 'Todd Phillips',
    cast: [
      { name: 'Joaquin Phoenix', role: 'Arthur Fleck / Joker' },
      { name: 'Robert De Niro', role: 'Murray Franklin' },
      { name: 'Zazie Beetz', role: 'Sophie Dumond' },
      { name: 'Frances Conroy', role: 'Penny Fleck' },
      { name: 'Brett Cullen', role: 'Thomas Wayne' }
    ],
    country: 'United States',
    watchedAt: '2025-07-03',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 7,
    isLogged: true,
  },
  {
    id: '33',
    original_title: 'The Pianist',
    year: 2002,
    spanish_title: 'El pianista',
    poster_path: 'https://image.tmdb.org/t/p/w500/2hFvxCCWrTmCYwfy7yum0GKRi3Y.jpg',
    runtime: '2h 30m',
    overview: 'A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.',
    genres: ['Drama', 'War'],
    rating: 8.5,
    director: 'Roman Polanski',
    cast: [
      { name: 'Adrien Brody', role: 'Władysław Szpilman' },
      { name: 'Thomas Kretschmann', role: 'Captain Wilm Hosenfeld' },
      { name: 'Frank Finlay', role: 'Janusz Korczak' },
      { name: 'Maureen Lipman', role: 'Grandmother' },
      { name: 'Ed Stoppard', role: 'Henryk Szpilman' }
    ],
    country: 'France',
    watchedAt: '2025-06-24',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 8,
    isLogged: true,
  },
  {
    id: '34',
    original_title: 'The Avengers',
    year: 2012,
    spanish_title: 'Los Vengadores',
    poster_path: 'https://www.themoviedb.org/t/p/w1280/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    runtime: '2h 23m',
    overview: 'Earth’s mightiest heroes must come together to stop Loki and his alien army from enslaving humanity.',
    genres: ['Action', 'Adventure', 'Science Fiction'],
    rating: 8.0,
    director: 'Joss Whedon',
    cast: [
      { name: 'Robert Downey Jr.', role: 'Tony Stark / Iron Man' },
      { name: 'Chris Evans', role: 'Steve Rogers / Captain America' },
      { name: 'Scarlett Johansson', role: 'Natasha Romanoff / Black Widow' },
      { name: 'Mark Ruffalo', role: 'Bruce Banner / Hulk' },
      { name: 'Chris Hemsworth', role: 'Thor' }
    ],
    country: 'United States',
    watchedAt: '2025-07-20',
        isWatched: true,
    isOnWatchlist: false,
    userRating: 5,
    isLogged: true,
  }
]
